// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: hello.proto

package com.tang.grpc.demo.service;

public final class HelloProto {
  private HelloProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\013hello.proto\022\022com.tang.grpc.demo\032\013model" +
      ".proto2\250\001\n\007Greeter\022N\n\010SayHello\022 .com.tan" +
      "g.grpc.demo.HelloRequest\032\036.com.tang.grpc" +
      ".demo.HelloReply\"\000\022M\n\007SayWhat\022 .com.tang" +
      ".grpc.demo.HelloRequest\032\036.com.tang.grpc." +
      "demo.HelloReply\"\000B/\n\032com.tang.grpc.demo." +
      "serviceB\nHelloProtoP\001\242\002\002TGb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.tang.grpc.demo.model.Model.getDescriptor(),
        }, assigner);
    com.tang.grpc.demo.model.Model.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
